/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardApisRouteImport } from './routes/_authenticated/dashboard/apis'
import { Route as AuthenticatedDashboardIpWhitelistRouteImport } from './routes/_authenticated/dashboard/ip-whitelist'
import { Route as AuthenticatedDashboardLogsRouteImport } from './routes/_authenticated/dashboard/logs'
import { Route as AuthenticatedDashboardTestApiRouteImport } from './routes/_authenticated/dashboard/test-api'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard/wallet'
import { Route as AuthenticatedDashboardWebhooksRouteImport } from './routes/_authenticated/dashboard/webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardApisRoute =
  AuthenticatedDashboardApisRouteImport.update({
    id: '/dashboard/apis',
    path: '/dashboard/apis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIpWhitelistRoute =
  AuthenticatedDashboardIpWhitelistRouteImport.update({
    id: '/dashboard/ip-whitelist',
    path: '/dashboard/ip-whitelist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardLogsRoute =
  AuthenticatedDashboardLogsRouteImport.update({
    id: '/dashboard/logs',
    path: '/dashboard/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTestApiRoute =
  AuthenticatedDashboardTestApiRouteImport.update({
    id: '/dashboard/test-api',
    path: '/dashboard/test-api',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/dashboard/wallet',
    path: '/dashboard/wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardWebhooksRoute =
  AuthenticatedDashboardWebhooksRouteImport.update({
    id: '/dashboard/webhooks',
    path: '/dashboard/webhooks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/logs': typeof LogsRoute
  '/status': typeof StatusRoute
  '/test-api': typeof TestApiRoute
  '/wallet': typeof WalletRoute
  '/webhooks': typeof WebhooksRoute
  '/dashboard/apis': typeof AuthenticatedDashboardApisRoute
  '/dashboard/ip-whitelist': typeof AuthenticatedDashboardIpWhitelistRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/dashboard/test-api': typeof AuthenticatedDashboardTestApiRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/logs': typeof LogsRoute
  '/status': typeof StatusRoute
  '/test-api': typeof TestApiRoute
  '/wallet': typeof WalletRoute
  '/webhooks': typeof WebhooksRoute
  '/dashboard/apis': typeof AuthenticatedDashboardApisRoute
  '/dashboard/ip-whitelist': typeof AuthenticatedDashboardIpWhitelistRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/dashboard/test-api': typeof AuthenticatedDashboardTestApiRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apis': typeof ApisRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/logs': typeof LogsRoute
  '/status': typeof StatusRoute
  '/test-api': typeof TestApiRoute
  '/wallet': typeof WalletRoute
  '/webhooks': typeof WebhooksRoute
  '/_authenticated/dashboard/apis': typeof AuthenticatedDashboardApisRoute
  '/_authenticated/dashboard/ip-whitelist': typeof AuthenticatedDashboardIpWhitelistRoute
  '/_authenticated/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/_authenticated/dashboard/test-api': typeof AuthenticatedDashboardTestApiRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/_authenticated/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apis'
    | '/auth'
    | '/docs'
    | '/logs'
    | '/status'
    | '/test-api'
    | '/wallet'
    | '/webhooks'
    | '/dashboard/apis'
    | '/dashboard/ip-whitelist'
    | '/dashboard/logs'
    | '/dashboard/test-api'
    | '/dashboard/wallet'
    | '/dashboard/webhooks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apis'
    | '/auth'
    | '/docs'
    | '/logs'
    | '/status'
    | '/test-api'
    | '/wallet'
    | '/webhooks'
    | '/dashboard/apis'
    | '/dashboard/ip-whitelist'
    | '/dashboard/logs'
    | '/dashboard/test-api'
    | '/dashboard/wallet'
    | '/dashboard/webhooks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apis'
    | '/auth'
    | '/docs'
    | '/logs'
    | '/status'
    | '/test-api'
    | '/wallet'
    | '/webhooks'
    | '/_authenticated/dashboard/apis'
    | '/_authenticated/dashboard/ip-whitelist'
    | '/_authenticated/dashboard/logs'
    | '/_authenticated/dashboard/test-api'
    | '/_authenticated/dashboard/wallet'
    | '/_authenticated/dashboard/webhooks'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApisRoute: typeof ApisRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  LogsRoute: typeof LogsRoute
  StatusRoute: typeof StatusRoute
  TestApiRoute: typeof TestApiRoute
  WalletRoute: typeof WalletRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/apis': {
      id: '/_authenticated/dashboard/apis'
      path: '/dashboard/apis'
      fullPath: '/dashboard/apis'
      preLoaderRoute: typeof AuthenticatedDashboardApisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ip-whitelist': {
      id: '/_authenticated/dashboard/ip-whitelist'
      path: '/dashboard/ip-whitelist'
      fullPath: '/dashboard/ip-whitelist'
      preLoaderRoute: typeof AuthenticatedDashboardIpWhitelistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/logs': {
      id: '/_authenticated/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof AuthenticatedDashboardLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/test-api': {
      id: '/_authenticated/dashboard/test-api'
      path: '/dashboard/test-api'
      fullPath: '/dashboard/test-api'
      preLoaderRoute: typeof AuthenticatedDashboardTestApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/webhooks': {
      id: '/_authenticated/dashboard/webhooks'
      path: '/dashboard/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof AuthenticatedDashboardWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardApisRoute: typeof AuthenticatedDashboardApisRoute
  AuthenticatedDashboardIpWhitelistRoute: typeof AuthenticatedDashboardIpWhitelistRoute
  AuthenticatedDashboardLogsRoute: typeof AuthenticatedDashboardLogsRoute
  AuthenticatedDashboardTestApiRoute: typeof AuthenticatedDashboardTestApiRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardWebhooksRoute: typeof AuthenticatedDashboardWebhooksRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardApisRoute: AuthenticatedDashboardApisRoute,
  AuthenticatedDashboardIpWhitelistRoute:
    AuthenticatedDashboardIpWhitelistRoute,
  AuthenticatedDashboardLogsRoute: AuthenticatedDashboardLogsRoute,
  AuthenticatedDashboardTestApiRoute: AuthenticatedDashboardTestApiRoute,
  AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
  AuthenticatedDashboardWebhooksRoute: AuthenticatedDashboardWebhooksRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApisRoute: ApisRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  LogsRoute: LogsRoute,
  StatusRoute: StatusRoute,
  TestApiRoute: TestApiRoute,
  WalletRoute: WalletRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
