export type ApiParam = {
  name: string;
  type: string;
  required?: boolean;
  desc: string;
};

export type ApiErrorCode = {
  code: number;
  meaning: string;
};

export type ApiEndpoint = {
  id: string;
  group: ApiGroup;
  method: "GET" | "POST" | "DELETE";
  path: string;
  title: string;
  desc: string;
  tags: string[];
  params: ApiParam[];
  /** Sample JSON body for POST endpoints */
  sampleBody?: Record<string, unknown>;
  /** Sample query string params for GET endpoints */
  sampleQuery?: Record<string, string>;
  /** Realistic sandbox response used by the Try-It console when no live provider is configured */
  sampleResponse: Record<string, unknown>;
  /** Realistic failed verification response (e.g. invalid entity/input combination) */
  sampleFailedResponse?: Record<string, unknown>;
  /** Possible HTTP error codes and meanings */
  errorCodes?: ApiErrorCode[];
  /** Status message on failed requests, e.g. "Refund processed" */
  statusMessage?: string;
  latency?: string;
};

export type ApiGroup = "KYC" | "Banking" | "Account Aggregator" | "Payments";

export const API_GROUPS: ApiGroup[] = ["KYC", "Banking", "Account Aggregator", "Payments"];

export const BASE_URL = "https://api.bharatapicloud.io/v1";

export const DEFAULT_ERROR_CODES: ApiErrorCode[] = [
  { code: 400, meaning: "Invalid request payload or malformed parameters." },
  { code: 401, meaning: "Unauthorized — missing, expired, or invalid API key." },
  { code: 404, meaning: "Requested resource or record does not exist." },
  { code: 412, meaning: "Precondition Failed — entity failed validation checks." },
  { code: 429, meaning: "Too Many Requests — plan rate limit or quota exceeded." },
  { code: 500, meaning: "Internal Server Error — server processing failure." },
  { code: 503, meaning: "Service Unavailable — upstream government/bank service down." },
  { code: 504, meaning: "Gateway Timeout — upstream source timed out." },
  { code: 505, meaning: "HTTP Version Not Supported." },
];

export const endpoints: ApiEndpoint[] = [
  /* ---------------- KYC ---------------- */
  {
    id: "verify-pan",
    group: "KYC",
    method: "POST",
    path: "/verify/pan",
    title: "Verify PAN",
    desc: "Validates a Permanent Account Number against the Income Tax Department database, with optional name and date-of-birth matching.",
    tags: ["pan", "income tax", "identity", "nsdl"],
    latency: "~1.4s",
    params: [
      { name: "pan", type: "string", required: true, desc: "10-character PAN, e.g. ABCDE1234F." },
      { name: "name", type: "string", desc: "Full name for fuzzy match against PAN records." },
      { name: "dob", type: "string (YYYY-MM-DD)", desc: "Date of birth for an additional match signal." },
    ],
    sampleBody: { pan: "ABCDE1234F", name: "Aarav Sharma", dob: "1990-04-12" },
    sampleResponse: {
      http_response_code: 200,
      result_code: 101,
      request_id: "bharat-dec5-11ef-bf40-cf31135d6ffc",
      client_ref_num: "ITV1_BEFISC",
      result: {
        pan: "BWSXXXXX2",
        pan_type: "Individual",
        fullname: "SXXXXXX",
        first_name: "SUXXXX",
        middle_name: "",
        last_name: "XXXXX",
        gender: "male",
        aadhaar_seeding_status: "Y",
        aadhaar_number: "XXXXXXXX1445",
        aadhaar_linked: true,
        dob: "07/11/1980",
        address: {
          building_name: "202XXXXXXXX",
          locality: "HXXXXXXXj",
          street_name: "JOXXXXXXD,",
          pincode: "2XXX01",
          city: "LUXXXXXXW",
          state: "UtXXXXXsh",
          country: "India",
        },
        mobile: "90XXXXXX34",
        email: "ab******************ol@gmail.com",
        name_match: true,
        name_match_score: 100,
      },
    },
    sampleFailedResponse: {
      http_response_code: 200,
      result_code: 102,
      request_id: "0199c2bb-4b54-8af1-80e4-5506bd8a86c7",
      client_ref_num: "testapis-jc36fwn",
      message: "Invalid Pan number or combination of inputs",
      result: {
        pan: "XXXXXXX",
        pan_status: "Invalid",
        pan_type: "",
        fullname: "",
        first_name: "",
        middle_name: "",
        last_name: "",
        gender: "",
        aadhaar_seeding_status: "",
        aadhaar_number: "",
        aadhaar_linked: "",
        dob: "",
        address: {
          building_name: "",
          locality: "",
          street_name: "",
          pincode: "",
          city: "",
          state: "",
          country: "",
        },
        mobile: "",
        email: "",
      },
    },
    errorCodes: [
      { code: 400, meaning: "Invalid parameter format or missing mandatory fields." },
      { code: 401, meaning: "Unauthorized — missing, revoked, or wrong-environment API key." },
      { code: 404, meaning: "Requested PAN or reference id does not exist in records." },
      { code: 412, meaning: "Precondition Failed — PAN status inactive or blocked." },
      { code: 429, meaning: "Plan rate limit or monthly quota exhausted." },
      { code: 500, meaning: "Internal Server Error — unexpected exception occurred." },
      { code: 503, meaning: "Service Unavailable — ITD/NSDL government portal is under maintenance." },
      { code: 504, meaning: "Gateway Timeout — Upstream government provider timed out." },
      { code: 505, meaning: "HTTP Version Not Supported." },
    ],
    statusMessage: "Refund processed",
  },
  {
    id: "aadhaar-otp",
    group: "KYC",
    method: "POST",
    path: "/verify/aadhaar/otp",
    title: "Aadhaar OTP (DigiLocker)",
    desc: "Step 1 of consent-based Aadhaar verification: sends an OTP to the Aadhaar-linked mobile number and returns a transaction id.",
    tags: ["aadhaar", "digilocker", "otp", "uidai", "consent"],
    latency: "~2.1s",
    params: [
      { name: "aadhaar_number", type: "string", required: true, desc: "12-digit Aadhaar number. Transmitted over TLS, never stored." },
      { name: "consent", type: "boolean", required: true, desc: "Must be true. User consent is mandatory." },
      { name: "consent_id", type: "string", desc: "Your reference to the captured consent artifact." },
    ],
    sampleBody: { aadhaar_number: "999999991234", consent: true, consent_id: "cns_9f21" },
    sampleResponse: { txn_id: "txn_digilocker_9a81f2", otp_sent: true, mobile_hint: "XXXXXX78XX", expires_in: 600 },
  },
  {
    id: "aadhaar-otp-confirm",
    group: "KYC",
    method: "POST",
    path: "/verify/aadhaar/otp/confirm",
    title: "Confirm Aadhaar OTP",
    desc: "Step 2 of Aadhaar verification: exchanges the OTP for the verified demographic KYC record and photo.",
    tags: ["aadhaar", "otp", "confirm", "ekyc"],
    latency: "~1.8s",
    params: [
      { name: "txn_id", type: "string", required: true, desc: "Transaction id returned by the OTP request." },
      { name: "otp", type: "string", required: true, desc: "6-digit OTP entered by the user." },
    ],
    sampleBody: { txn_id: "txn_digilocker_9a81f2", otp: "123456" },
    sampleResponse: {
      status: "verified",
      name: "Aarav Sharma",
      dob: "1990-04-12",
      gender: "M",
      address: { house: "12B", street: "MG Road", district: "Pune", state: "Maharashtra", pincode: "411001" },
      photo_base64: "/9j/4AAQSkZJRgABAQ...",
      request_id: "kyc_2c7e9f44",
    },
  },
  {
    id: "aadhaar-without-otp",
    group: "KYC",
    method: "POST",
    path: "/srv3/verification/aadhar",
    title: "Aadhar Fetch (Without OTP)",
    desc: "Instant Aadhaar number validation and demographic verification without requiring mobile OTP. Returns Aadhaar validity, age band, gender, state and masked mobile digits.",
    tags: ["aadhaar", "without otp", "direct", "uidai", "kyc"],
    latency: "~1.2s",
    params: [
      { name: "aadhaar", type: "string", required: true, desc: "12-digit Aadhaar number to validate." },
      { name: "name", type: "string", desc: "Optional full name for demographic matching." },
    ],
    sampleBody: { aadhaar: "999999991234", name: "Aarav Sharma" },
    sampleResponse: {
      http_response_code: 200,
      result_code: 101,
      request_id: "bharat-aadh-9912a7bf3",
      status: "valid",
      result: {
        aadhaar_number: "XXXXXXXX1234",
        is_valid: true,
        age_band: "30-40",
        gender: "M",
        state: "Maharashtra",
        mobile_digits: "XXX-XXX-7890",
        name_match: true,
        name_match_score: 100,
      },
    },
  },
  {
    id: "mobile-to-prefill",
    group: "KYC",
    method: "POST",
    path: "/kyc/mobile-prefill",
    title: "Mobile to Prefill",
    desc: "Fetch verified identity profile, PAN, Date of Birth, age, gender, email, and registered addresses pre-filled directly from user's registered mobile number and name.",
    tags: ["mobile", "prefill", "kyc", "identity", "telecom", "pan", "address"],
    latency: "~1.1s",
    params: [
      { name: "mobile_number", type: "string", required: true, desc: "10-digit registered mobile number." },
      { name: "first_name", type: "string", required: true, desc: "First name of the individual." },
      { name: "last_name", type: "string", required: true, desc: "Last name of the individual." },
    ],
    sampleBody: {
      mobile_number: "9876543210",
      first_name: "Som",
      last_name: "Kumar",
    },
    sampleResponse: {
      request_id: "6210ff90-025XXXXX4524f",
      result_code: 101,
      message: "success",
      result: {
        name: "SOM KUMAR",
        dob: "26-12-1990",
        age: "35",
        gender: "MALE",
        pan: "ERXXXXXX76K",
        email: "som.kumar@example.com",
        address: [
          {
            first_line_of_address: "FLAT 402, SHIVAM APARTMENTS",
            second_line_of_address: "SECTOR 18, NEAR CITY CENTER",
            third_line_of_address: "NOIDA, GAUTAM BUDDHA NAGAR, UP - 201301",
          },
        ],
      },
    },
    sampleFailedResponse: {
      request_id: "6210ff90-025XXXXX4524f",
      result_code: 102,
      message: "No profile records found for the provided mobile number and name combination",
      result: null,
    },
    errorCodes: [
      { code: 400, meaning: "Invalid mobile number format or missing required name fields." },
      { code: 401, meaning: "Unauthorized — missing, expired, or invalid API key." },
      { code: 404, meaning: "No prefill identity profile found for this phone number." },
      { code: 429, meaning: "Too Many Requests — plan rate limit or quota exceeded." },
      { code: 500, meaning: "Internal Server Error — server processing failure." },
      { code: 503, meaning: "Service Unavailable — telecom/identity database under maintenance." },
    ],
    statusMessage: "Refund processed",
  },
  {
    id: "mobile-name-finder",
    group: "KYC",
    method: "POST",
    path: "/srv2/mobile-name-finder",
    title: "Mobile To Name Finder",
    desc: "Instant name lookup and telecom subscriber verification. Fetch the registered subscriber legal name and telecom circle details directly from a 10-digit mobile number.",
    tags: ["mobile", "name finder", "telecom", "kyc", "subscriber", "identity"],
    latency: "~1.0s",
    params: [
      { name: "mobile", type: "string", required: true, desc: "10-digit registered mobile number." },
    ],
    sampleBody: {
      mobile: "9876543210",
    },
    sampleResponse: {
      status: {
        code: 200,
        type: "success",
        message: "Request processed successfully.",
      },
      result_code: 101,
      message: "success",
      data: {
        mobile: "9876543210",
        full_name: "SHUBHAM GUPTA",
        first_name: "SHUBHAM",
        last_name: "GUPTA",
        operator: "AIRTEL",
        circle: "DELHI NCR",
        status: "VALID",
        is_valid: true,
      },
    },
    sampleFailedResponse: {
      status: {
        code: 404,
        type: "error",
        message: "No subscriber records found for the provided mobile number.",
      },
      result_code: 102,
      message: "Subscriber Not Found",
      data: null,
    },
    errorCodes: [
      { code: 400, meaning: "Invalid mobile number format or missing mobile parameter." },
      { code: 401, meaning: "Unauthorized — missing, expired, or invalid API credentials." },
      { code: 402, meaning: "Insufficient wallet balance (Requires ₹5.00 per request)." },
      { code: 404, meaning: "No subscriber profile found for this phone number." },
      { code: 429, meaning: "Too Many Requests — plan rate limit or quota exceeded." },
      { code: 500, meaning: "Internal Server Error — server processing failure." },
      { code: 503, meaning: "Service Unavailable — upstream telecom database under maintenance." },
    ],
    statusMessage: "Refund processed",
  },
  {
    id: "requester-ip-lookup",
    group: "KYC",
    method: "GET",
    path: "/check",
    title: "Requester IP Lookup",
    desc: "Instant geolocation and network intelligence for incoming or specified IP addresses. Returns city, region, coordinates, country flag, calling code, and connection profile via APILAYER.",
    tags: ["ip", "geolocation", "apilayer", "network", "location", "ipstack"],
    latency: "~0.7s",
    params: [
      { name: "ip", type: "string", required: false, desc: "Optional IPv4/IPv6 address. If omitted, automatically detects caller IP." },
    ],
    sampleBody: {
      ip: "122.162.144.131",
    },
    sampleResponse: {
      ip: "122.162.144.131",
      type: "ipv4",
      continent_code: "AS",
      continent_name: "Asia",
      country_code: "IN",
      country_name: "India",
      region_code: "DL",
      region_name: "Delhi",
      city: "New Delhi",
      zip: "110001",
      latitude: 28.6352996826172,
      longitude: 77.2249984741211,
      msa: null,
      dma: null,
      radius: "0",
      ip_routing_type: "fixed",
      connection_type: "tx",
      location: {
        geoname_id: 1261481,
        capital: "New Delhi",
        languages: [
          { code: "hi", name: "Hindi", native: "हिन्दी" },
          { code: "en", name: "English", native: "English" },
        ],
        country_flag: "https://assets.ipstack.com/flags/in.svg",
        country_flag_emoji: "🇮🇳",
        country_flag_emoji_unicode: "U+1F1EE U+1F1F3",
        calling_code: "91",
        is_eu: false,
      },
    },
    sampleFailedResponse: {
      success: false,
      error: {
        code: 104,
        type: "usage_limit_reached",
        info: "Your monthly usage limit has been reached. Please upgrade your subscription plan.",
      },
    },
    errorCodes: [
      { code: 400, meaning: "Invalid IP address format." },
      { code: 404, meaning: "No geolocation record found for provided IP address." },
      { code: 429, meaning: "Too Many Requests — plan rate limit or quota exceeded." },
      { code: 500, meaning: "Internal Server Error — server processing failure." },
      { code: 503, meaning: "Service Unavailable — upstream APILAYER service unreachable." },
    ],
  },
  {
    id: "reverse-geocoding",
    group: "KYC",
    method: "GET",
    path: "/reverse",
    title: "Reverse Geocoding",
    desc: "Resolve GPS coordinates (latitude & longitude) into full geographic address, road, landmark, city, state, postal code, and administrative boundaries using OpenStreetMap Nominatim.",
    tags: ["gps", "geocoding", "reverse", "location", "address", "coordinates", "osm"],
    latency: "~320ms",
    params: [
      { name: "lat", type: "number", required: true, desc: "Latitude coordinate (-90.0 to 90.0), e.g. 28.6139." },
      { name: "lon", type: "number", required: true, desc: "Longitude coordinate (-180.0 to 180.0), e.g. 77.2090." },
    ],
    sampleRequest: {
      lat: 28.6139,
      lon: 77.2090,
    },
    sampleResponse: {
      place_id: 244382395,
      licence: "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
      osm_type: "way",
      osm_id: 1307222666,
      lat: "28.6139094",
      lon: "77.2090007",
      class: "highway",
      type: "secondary",
      place_rank: 26,
      importance: 0.05341081483176925,
      addresstype: "road",
      name: "Kartavya Path",
      display_name: "Kartavya Path, Raisina Hill, New Delhi, Delhi, 110004, India",
      address: {
        road: "Kartavya Path",
        suburb: "Raisina Hill",
        city: "New Delhi",
        state_district: "New Delhi",
        state: "Delhi",
        "ISO3166-2-lvl4": "IN-DL",
        postcode: "110004",
        country: "India",
        country_code: "in",
      },
      boundingbox: ["28.6137596", "28.6139270", "77.2087730", "77.2121071"],
    },
    sampleError: {
      error: "Unable to geocode",
    },
    errorCodes: [
      { code: 400, meaning: "Invalid latitude or longitude coordinate." },
      { code: 401, meaning: "Unauthorized: Missing required Bharat API credentials (api_id, api_key, token_id)." },
      { code: 404, meaning: "No address record found for provided coordinates." },
      { code: 500, meaning: "Internal Server Error — server processing failure." },
      { code: 503, meaning: "Service Unavailable — upstream Nominatim service unreachable." },
    ],
  },
  {
    id: "verify-gstin",
    group: "KYC",
    method: "POST",
    path: "/verify/gstin",
    title: "Verify GSTIN",
    desc: "Fetches GST registration details, filing status and the registered business address for a GSTIN.",
    tags: ["gstin", "gst", "business", "kyb"],
    latency: "~1.1s",
    params: [
      { name: "gstin", type: "string", required: true, desc: "15-character GSTIN, e.g. 27AAECV1234C1ZP." },
    ],
    sampleBody: { gstin: "27AAECV1234C1ZP" },
    sampleResponse: {
      status: "verified",
      legal_name: "Bharat API Cloud Technologies Private Limited",
      trade_name: "Bharat API Cloud",
      registration_date: "2019-07-01",
      gst_status: "Active",
      taxpayer_type: "Regular",
      state_jurisdiction: "Maharashtra",
      request_id: "kyb_71ac0e",
    },
  },
  {
    id: "verify-cin",
    group: "KYC",
    method: "POST",
    path: "/verify/cin",
    title: "Verify CIN (MCA)",
    desc: "Looks up company master data from the MCA registry, including directors, status and paid-up capital.",
    tags: ["cin", "mca", "company", "kyb", "directors"],
    latency: "~1.9s",
    params: [{ name: "cin", type: "string", required: true, desc: "21-character Corporate Identification Number." }],
    sampleBody: { cin: "U72900PN2019PTC185432" },
    sampleResponse: {
      status: "verified",
      company_name: "Bharat API Cloud Technologies Private Limited",
      company_status: "Active",
      incorporation_date: "2019-06-24",
      paid_up_capital: 1000000,
      registered_address: "5th Floor, Amar Tech Park, Pune 411014",
      directors: [{ din: "08123456", name: "Aarav Sharma" }],
      request_id: "kyb_5cc9a1",
    },
  },
  {
    id: "document-ocr",
    group: "KYC",
    method: "POST",
    path: "/kyc/ocr",
    title: "Document OCR",
    desc: "Extracts structured fields from an ID document image or PDF and flags tampering signals.",
    tags: ["ocr", "document", "extract", "tamper"],
    latency: "~2.6s",
    params: [
      { name: "document_type", type: "string", required: true, desc: "One of pan, aadhaar, passport, dl, voter_id, cheque." },
      { name: "file_url", type: "string", required: true, desc: "HTTPS URL or base64 data URI of the document." },
    ],
    sampleBody: { document_type: "pan", file_url: "https://files.example.com/pan-front.jpg" },
    sampleResponse: {
      status: "extracted",
      document_type: "pan",
      fields: { pan: "ABCDE1234F", name: "AARAV SHARMA", father_name: "RAJESH SHARMA", dob: "12/04/1990" },
      tamper_score: 0.03,
      confidence: 0.97,
      request_id: "ocr_3ab19c",
    },
  },
  {
    id: "face-liveness",
    group: "KYC",
    method: "POST",
    path: "/kyc/face-match",
    title: "Face match & liveness",
    desc: "Compares a selfie against an ID photo and returns a passive liveness score to block spoof attempts.",
    tags: ["face", "liveness", "selfie", "biometric", "spoof"],
    latency: "~1.7s",
    params: [
      { name: "selfie_url", type: "string", required: true, desc: "HTTPS URL or base64 selfie captured live." },
      { name: "id_photo_url", type: "string", required: true, desc: "HTTPS URL or base64 photo cropped from the ID." },
      { name: "check_liveness", type: "boolean", desc: "Defaults to true. Runs passive liveness detection." },
    ],
    sampleBody: { selfie_url: "https://files.example.com/selfie.jpg", id_photo_url: "https://files.example.com/id.jpg", check_liveness: true },
    sampleResponse: { status: "match", match_score: 0.94, liveness: "real", liveness_score: 0.99, request_id: "face_6e2b8f" },
  },
  {
    id: "verify-voter-id",
    group: "KYC",
    method: "POST",
    path: "/verify/voter-id",
    title: "Verify Voter ID",
    desc: "Validates an EPIC number against the Election Commission roll and returns the elector record.",
    tags: ["voter", "epic", "election commission"],
    latency: "~1.5s",
    params: [{ name: "epic_number", type: "string", required: true, desc: "Voter ID / EPIC number." }],
    sampleBody: { epic_number: "ABC1234567" },
    sampleResponse: {
      status: "verified",
      name: "Aarav Sharma",
      relation_name: "Rajesh Sharma",
      assembly_constituency: "Pune Cantonment",
      state: "Maharashtra",
      request_id: "kyc_voter_44a1",
    },
  },
  {
    id: "verify-dl",
    group: "KYC",
    method: "POST",
    path: "/verify/driving-licence",
    title: "Verify Driving Licence",
    desc: "Validates a driving licence number against the Sarathi/Parivahan database with vehicle class details.",
    tags: ["driving licence", "dl", "parivahan", "sarathi"],
    latency: "~2.0s",
    params: [
      { name: "dl_number", type: "string", required: true, desc: "Driving licence number, e.g. MH12 20190001234." },
      { name: "dob", type: "string (YYYY-MM-DD)", required: true, desc: "Date of birth of the licence holder." },
    ],
    sampleBody: { dl_number: "MH1220190001234", dob: "1990-04-12" },
    sampleResponse: {
      status: "verified",
      name: "Aarav Sharma",
      issue_date: "2019-02-11",
      valid_until: "2039-04-11",
      vehicle_classes: ["LMV", "MCWG"],
      issuing_rto: "Pune (MH12)",
      request_id: "kyc_dl_9812",
    },
  },
  {
    id: "verify-passport",
    group: "KYC",
    method: "POST",
    path: "/verify/passport",
    title: "Verify Passport",
    desc: "Validates a passport file number and date of birth against the Passport Seva records.",
    tags: ["passport", "psk", "travel document"],
    latency: "~2.3s",
    params: [
      { name: "file_number", type: "string", required: true, desc: "Passport application file number." },
      { name: "dob", type: "string (YYYY-MM-DD)", required: true, desc: "Date of birth on the passport." },
    ],
    sampleBody: { file_number: "PN1234567890123", dob: "1990-04-12" },
    sampleResponse: {
      status: "verified",
      name: "AARAV SHARMA",
      passport_type: "P",
      application_type: "fresh",
      issue_date: "2021-08-04",
      request_id: "kyc_pp_1f7c",
    },
  },
  {
    id: "aml-screening",
    group: "KYC",
    method: "POST",
    path: "/kyc/aml-screen",
    title: "AML / PEP screening",
    desc: "Screens a name against global sanctions, PEP and adverse-media watchlists with fuzzy matching.",
    tags: ["aml", "pep", "sanctions", "watchlist", "risk"],
    latency: "~1.2s",
    params: [
      { name: "name", type: "string", required: true, desc: "Full legal name of the individual or entity." },
      { name: "dob", type: "string (YYYY-MM-DD)", desc: "Improves precision and reduces false positives." },
      { name: "country", type: "string", desc: "ISO 3166-1 alpha-2 country code." },
    ],
    sampleBody: { name: "Aarav Sharma", dob: "1990-04-12", country: "IN" },
    sampleResponse: {
      status: "clear",
      risk_level: "low",
      matches: [],
      lists_checked: ["OFAC SDN", "UN Consolidated", "EU", "RBI Caution", "Interpol", "Adverse Media"],
      request_id: "aml_7d20b3",
    },
  },

  /* ---------------- Banking ---------------- */
  {
    id: "bank-penny-less",
    group: "Banking",
    method: "POST",
    path: "/bank/verify/penny-less",
    title: "Bank Verification Penny Less V2",
    desc: "Instant bank account validation and beneficiary name verification without performing a financial penny deposit. Validates bank account status, registered name, and IFSC details directly.",
    tags: ["penny less", "bank verification", "account validation", "ifsc", "banking"],
    latency: "~1.5s",
    params: [
      { name: "creditorAccountId", type: "string", required: true, desc: "Bank Account Number to verify." },
      { name: "ifscCode", type: "string", required: true, desc: "11-character Bank IFSC Code, e.g. SBIN0001234." },
    ],
    sampleBody: { creditorAccountId: "123456789012", ifscCode: "HDFC0000001" },
    sampleResponse: {
      status: {
        code: 200,
        type: "success",
        message: "Request processed successfully.",
      },
      message: "Request processed successfully.",
      data: {
        account_status: "VALID",
        beneficiary_name: "SHUBHAM GUPTA",
        account_number: "XXXXXXXX9012",
        ifsc: "HDFC0000001",
        bank_name: "HDFC Bank",
        branch: "Main Branch",
        city: "Mumbai",
        state: "Maharashtra",
        is_active: true,
      },
    },
  },
  {
    id: "bank-penny-drop",
    group: "Banking",
    method: "POST",
    path: "/bank/verify",
    title: "Bank verification (penny drop)",
    desc: "Credits ₹1 to the account to confirm it is live and returns the beneficiary name registered with the bank.",
    tags: ["penny drop", "bank account", "beneficiary", "imps"],
    latency: "~3.2s",
    params: [
      { name: "account_number", type: "string", required: true, desc: "Beneficiary bank account number." },
      { name: "ifsc", type: "string", required: true, desc: "11-character IFSC of the branch." },
      { name: "name", type: "string", desc: "Expected account holder name for fuzzy matching." },
    ],
    sampleBody: { account_number: "50100123456789", ifsc: "HDFC0000123", name: "Aarav Sharma" },
    sampleResponse: {
      status: "verified",
      account_exists: true,
      beneficiary_name: "AARAV SHARMA",
      name_match: "exact",
      match_score: 0.99,
      bank: "HDFC Bank",
      branch: "MG Road, Pune",
      utr: "HDFC2408291234567",
      request_id: "bank_4f81cd",
    },
  },
  {
    id: "bank-reverse-penny",
    group: "Banking",
    method: "POST",
    path: "/bank/reverse-penny-drop",
    title: "Reverse penny drop",
    desc: "Creates a collect request the user pays ₹1 against, verifying account ownership without a name match.",
    tags: ["reverse penny drop", "upi collect", "ownership"],
    latency: "~0.9s",
    params: [
      { name: "customer_ref", type: "string", required: true, desc: "Your internal reference for the user." },
      { name: "redirect_url", type: "string", desc: "Where to send the user after payment." },
    ],
    sampleBody: { customer_ref: "user_8812", redirect_url: "https://yourapp.com/kyc/return" },
    sampleResponse: {
      status: "pending",
      collect_id: "rpd_71ba3c",
      payment_link: "https://pay.bharatapicloud.io/rpd_71ba3c",
      expires_in: 900,
      request_id: "bank_rpd_02f9",
    },
  },
  {
    id: "ifsc-lookup",
    group: "Banking",
    method: "GET",
    path: "/bank/ifsc/{ifsc}",
    title: "IFSC lookup",
    desc: "Returns branch details and supported payment rails for an IFSC code.",
    tags: ["ifsc", "branch", "neft", "rtgs", "lookup"],
    latency: "~120ms",
    params: [{ name: "ifsc", type: "path string", required: true, desc: "11-character IFSC code." }],
    sampleQuery: { ifsc: "HDFC0000123" },
    sampleResponse: {
      ifsc: "HDFC0000123",
      bank: "HDFC Bank",
      branch: "MG Road, Pune",
      address: "Nucleus Mall, Church Road, Pune 411001",
      city: "PUNE",
      state: "MAHARASHTRA",
      micr: "411240002",
      rails: { neft: true, rtgs: true, imps: true, upi: true },
    },
  },
  {
    id: "upi-vpa",
    group: "Banking",
    method: "POST",
    path: "/bank/upi/validate",
    title: "Validate UPI VPA",
    desc: "Checks whether a UPI ID is active and returns the registered payee name.",
    tags: ["upi", "vpa", "payee", "validate"],
    latency: "~800ms",
    params: [{ name: "vpa", type: "string", required: true, desc: "UPI handle, e.g. aarav@okhdfcbank." }],
    sampleBody: { vpa: "aarav@okhdfcbank" },
    sampleResponse: { status: "verified", vpa_valid: true, payee_name: "AARAV SHARMA", psp: "okhdfcbank", request_id: "upi_2b91fe" },
  },
  {
    id: "bank-statement",
    group: "Banking",
    method: "POST",
    path: "/bank/statement/analyse",
    title: "Bank statement analysis",
    desc: "Parses a PDF bank statement and returns income, obligations, bounce count and a cash-flow summary.",
    tags: ["statement", "underwriting", "income", "analysis", "lending"],
    latency: "~6.4s",
    params: [
      { name: "file_url", type: "string", required: true, desc: "HTTPS URL of the PDF statement." },
      { name: "password", type: "string", desc: "PDF password if the statement is protected." },
    ],
    sampleBody: { file_url: "https://files.example.com/statement.pdf", password: "AARA1204" },
    sampleResponse: {
      status: "analysed",
      account_holder: "AARAV SHARMA",
      period: { from: "2026-02-01", to: "2026-07-31" },
      average_monthly_credit: 184500,
      average_monthly_debit: 141200,
      salary_detected: true,
      emi_obligations: 23400,
      bounced_cheques: 0,
      request_id: "stmt_9c31a7",
    },
  },

  /* ---------------- Account Aggregator ---------------- */
  {
    id: "aa-consent",
    group: "Account Aggregator",
    method: "POST",
    path: "/aa/consent",
    title: "Create consent request",
    desc: "Creates an RBI Account Aggregator consent request and returns the redirect URL for the user journey.",
    tags: ["account aggregator", "consent", "rbi", "sahamati"],
    latency: "~1.0s",
    params: [
      { name: "customer_mobile", type: "string", required: true, desc: "Mobile number linked to the user's bank accounts." },
      { name: "fi_types", type: "string[]", required: true, desc: "e.g. [\"DEPOSIT\", \"TERM_DEPOSIT\"]." },
      { name: "purpose_code", type: "string", required: true, desc: "AA purpose code, e.g. 101 for wealth management." },
      { name: "duration_days", type: "integer", desc: "Consent validity window. Defaults to 30." },
    ],
    sampleBody: { customer_mobile: "9876543210", fi_types: ["DEPOSIT"], purpose_code: "101", duration_days: 30 },
    sampleResponse: {
      consent_handle: "cn_8f2a1b7c",
      status: "PENDING",
      redirect_url: "https://aa.bharatapicloud.io/consent/cn_8f2a1b7c",
      expires_at: "2026-08-30T08:00:00Z",
    },
  },
  {
    id: "aa-consent-status",
    group: "Account Aggregator",
    method: "GET",
    path: "/aa/consent/{consent_handle}",
    title: "Consent status",
    desc: "Returns the current state of a consent handle and the linked accounts once approved.",
    tags: ["account aggregator", "consent status", "linked accounts"],
    latency: "~150ms",
    params: [{ name: "consent_handle", type: "path string", required: true, desc: "Handle returned when the consent was created." }],
    sampleQuery: { consent_handle: "cn_8f2a1b7c" },
    sampleResponse: {
      consent_handle: "cn_8f2a1b7c",
      status: "ACTIVE",
      consent_id: "cid_44f0a2",
      accounts: [{ fip: "HDFC", masked_account: "XXXXXX6789", fi_type: "DEPOSIT" }],
      approved_at: "2026-08-29T07:55:12Z",
    },
  },
  {
    id: "aa-fetch-fi",
    group: "Account Aggregator",
    method: "POST",
    path: "/aa/fi/fetch",
    title: "Fetch financial data",
    desc: "Requests a financial information session for an active consent and returns decrypted transaction data.",
    tags: ["account aggregator", "fi fetch", "transactions", "session"],
    latency: "~4.8s",
    params: [
      { name: "consent_id", type: "string", required: true, desc: "Active consent id." },
      { name: "from", type: "string (ISO 8601)", required: true, desc: "Start of the data range." },
      { name: "to", type: "string (ISO 8601)", required: true, desc: "End of the data range." },
    ],
    sampleBody: { consent_id: "cid_44f0a2", from: "2026-05-01T00:00:00Z", to: "2026-08-01T00:00:00Z" },
    sampleResponse: {
      session_id: "sess_1ad9c4",
      status: "COMPLETED",
      accounts: [
        {
          masked_account: "XXXXXX6789",
          balance: 148230.55,
          transactions: [
            { date: "2026-07-31", type: "CREDIT", amount: 185000, narration: "SALARY JUL 2026" },
            { date: "2026-07-05", type: "DEBIT", amount: 23400, narration: "EMI HDFC LOAN" },
          ],
        },
      ],
    },
  },

  /* ---------------- Payments ---------------- */
  {
    id: "create-payout",
    group: "Payments",
    method: "POST",
    path: "/payouts",
    title: "Create payout",
    desc: "Sends money to a bank account or UPI handle over IMPS, NEFT, RTGS or UPI with idempotency support.",
    tags: ["payout", "imps", "neft", "disbursal", "transfer"],
    latency: "~2.4s",
    params: [
      { name: "amount", type: "integer (paise)", required: true, desc: "Amount in paise, e.g. 250000 for ₹2,500." },
      { name: "mode", type: "string", required: true, desc: "One of IMPS, NEFT, RTGS, UPI." },
      { name: "beneficiary", type: "object", required: true, desc: "Account number + IFSC, or a UPI VPA." },
      { name: "reference", type: "string", desc: "Your internal payout reference." },
    ],
    sampleBody: {
      amount: 250000,
      mode: "IMPS",
      beneficiary: { name: "Aarav Sharma", account_number: "50100123456789", ifsc: "HDFC0000123" },
      reference: "payout_8812",
    },
    sampleResponse: {
      payout_id: "po_5ab19f",
      status: "processing",
      amount: 250000,
      mode: "IMPS",
      utr: null,
      created_at: "2026-08-29T08:12:44Z",
    },
  },
  {
    id: "payout-status",
    group: "Payments",
    method: "GET",
    path: "/payouts/{payout_id}",
    title: "Payout status",
    desc: "Returns the current state of a payout including the bank UTR once settled.",
    tags: ["payout", "status", "utr", "settlement"],
    latency: "~110ms",
    params: [{ name: "payout_id", type: "path string", required: true, desc: "Payout id returned at creation." }],
    sampleQuery: { payout_id: "po_5ab19f" },
    sampleResponse: {
      payout_id: "po_5ab19f",
      status: "success",
      amount: 250000,
      utr: "HDFCN2408291234567",
      settled_at: "2026-08-29T08:13:02Z",
    },
  },
  {
    id: "create-va",
    group: "Payments",
    method: "POST",
    path: "/virtual-accounts",
    title: "Create virtual account",
    desc: "Issues a dedicated virtual account and UPI handle so inbound collections auto-reconcile to one customer.",
    tags: ["virtual account", "collections", "reconciliation", "va"],
    latency: "~1.3s",
    params: [
      { name: "customer_ref", type: "string", required: true, desc: "Your customer identifier for reconciliation." },
      { name: "name", type: "string", required: true, desc: "Display name on the virtual account." },
    ],
    sampleBody: { customer_ref: "user_8812", name: "Aarav Sharma" },
    sampleResponse: {
      va_id: "va_71cc03",
      account_number: "VERO8812004421",
      ifsc: "YESB0CMSNOC",
      vpa: "vero.user8812@yesbank",
      status: "active",
    },
  },
  {
    id: "va-transactions",
    group: "Payments",
    method: "GET",
    path: "/virtual-accounts/{va_id}/transactions",
    title: "VA transactions",
    desc: "Lists credits received on a virtual account with payer details for reconciliation.",
    tags: ["virtual account", "transactions", "credits", "payer"],
    latency: "~180ms",
    params: [
      { name: "va_id", type: "path string", required: true, desc: "Virtual account id." },
      { name: "limit", type: "integer", desc: "Page size, max 100. Defaults to 25." },
    ],
    sampleQuery: { va_id: "va_71cc03", limit: "25" },
    sampleResponse: {
      va_id: "va_71cc03",
      count: 1,
      transactions: [
        {
          txn_id: "vatxn_9f21a0",
          amount: 500000,
          utr: "SBIN2408291112233",
          payer_name: "MEERA IYER",
          payer_account: "XXXXXX4321",
          received_at: "2026-08-29T06:41:10Z",
        },
      ],
    },
  },
  {
    id: "refund-payout",
    group: "Payments",
    method: "POST",
    path: "/payouts/{payout_id}/reverse",
    title: "Reverse a payout",
    desc: "Requests reversal of a payout that failed at the beneficiary bank and returns the reversal reference.",
    tags: ["reversal", "refund", "failed payout"],
    latency: "~1.6s",
    params: [
      { name: "payout_id", type: "path string", required: true, desc: "Payout to reverse." },
      { name: "reason", type: "string", desc: "Free-text reason recorded on the reversal." },
    ],
    sampleBody: { payout_id: "po_5ab19f", reason: "beneficiary_account_closed" },
    sampleResponse: { reversal_id: "rv_11c8b2", payout_id: "po_5ab19f", status: "initiated", amount: 250000 },
  },
];

export const WEBHOOK_EVENTS = [
  "kyc.verification.completed",
  "kyc.verification.failed",
  "bank.verification.completed",
  "aa.consent.approved",
  "aa.fi.data.ready",
  "payout.success",
  "payout.failed",
  "va.credit.received",
] as const;

export type WebhookEventType = (typeof WEBHOOK_EVENTS)[number];

export function getEndpoint(id: string): ApiEndpoint | undefined {
  return endpoints.find((e) => e.id === id);
}

/** Fills path placeholders like /payouts/{payout_id} from a params object. */
export function resolvePath(path: string, values: Record<string, string>): string {
  return path.replace(/\{(\w+)\}/g, (_m, key: string) => values[key] ?? `{${key}}`);
}

export function sampleInput(endpoint: ApiEndpoint): Record<string, unknown> {
  return endpoint.sampleBody ?? endpoint.sampleQuery ?? {};
}
